
--pivot
SELECT *
FROM (
    SELECT
        EXTRACT(YEAR FROM v.data_vanzare) AS an,
        a.moneda,
        v.cantitate * a.pret AS suma_incasata
    FROM
        Vanzari v
        JOIN Articole a ON v.articol_id = a.articol_id
    WHERE
        a.moneda IN ('RON', 'EUR', 'USD')
)
PIVOT (
    SUM(suma_incasata)
    FOR moneda IN ('RON' AS RON, 'EUR' AS EUR, 'USD' AS USD)
)
ORDER BY an;

--grouping sets
SELECT 
    TO_CHAR(v.data_vanzare, 'YYYY') AS an,
    TO_CHAR(v.data_vanzare, 'MM') AS luna,
    TO_CHAR(v.data_vanzare, 'Q') AS trimestru,
    a.moneda,
    SUM(v.cantitate*a.pret) AS total_cantitate
FROM Vanzari v
 JOIN Articole a ON v.articol_id = a.articol_id
GROUP BY GROUPING SETS (
    (TO_CHAR(v.data_vanzare, 'YYYY'), TO_CHAR(v.data_vanzare, 'MM'), a.moneda),      -- lunar + an + moneda
    (TO_CHAR(v.data_vanzare, 'YYYY'), TO_CHAR(v.data_vanzare, 'Q'), a.moneda),       -- trimestru + an + moneda
    (TO_CHAR(v.data_vanzare, 'YYYY'), a.moneda)                                     -- an + moneda
)
ORDER BY an, luna, trimestru, moneda;
 
--analytics
SELECT *
FROM (
    SELECT
        v.vanzare_id,
        a.articol_id,
        a.nume AS articol_nume,
        a.moneda,
        v.data_vanzare,
        v.cantitate,
        a.pret,
        v.cantitate * a.pret AS valoare,
        RANK() OVER (
            PARTITION BY a.moneda
            ORDER BY v.cantitate * a.pret DESC
        ) AS rnk
    FROM
        Vanzari v
        JOIN Articole a ON v.articol_id = a.articol_id
    WHERE
        v.data_vanzare >= TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM')  -- prima zi a lunii trecute
    AND
        v.data_vanzare < TRUNC(SYSDATE, 'MM')                   -- prima zi a lunii curente
)
WHERE rnk <= 10
ORDER BY moneda, rnk;

select * from employees;

--hierarchical

SELECT employee_id,
       first_name,
       last_name,
       manager_id,
       LEVEL AS hierarchy_level
FROM employees
START WITH manager_id IS NULL
CONNECT BY PRIOR employee_id = manager_id;


WITH employee_hierarchy (employee_id, first_name, last_name, manager_id, hierarchy_level) AS (
    SELECT 
        employee_id,
        first_name,
        last_name,
        manager_id,
        1 AS hierarchy_level
    FROM employees
    WHERE manager_id IS NULL

    UNION ALL

    SELECT 
        e.employee_id,
        e.first_name,
        e.last_name,
        e.manager_id,
        eh.hierarchy_level + 1
    FROM employees e
    JOIN employee_hierarchy eh ON e.manager_id = eh.employee_id
)
SELECT * FROM employee_hierarchy;

--generate rows
SELECT ADD_MONTHS (TRUNC (SYSDATE, 'MM') - 1, -ROWNUM + 1) month_end,
      TO_CHAR (ADD_MONTHS (TRUNC (SYSDATE, 'MM') - 1, -ROWNUM + 1), 'MM') month_no
      FROM DUAL CONNECT BY ROWNUM < 13;


--json
select json_object(*) from employees;
select json_object(first_name,last_name, hire_date) from employees;
select json_object('nume' value first_name||' '||last_name, hire_date) from employees;
select json_object(
  'department' value d.department_name,
  'employees' value (
    select json_arrayagg(
      json_object(
        'nume' value e.first_name||' '||e.last_name
      )
    )
    from employees e
    where e.department_id = d.department_id
  )
) as department_json
from departments d;

with json_data as (
    select '{"department":"Purchasing","employees":[{"nume":"Den Li"},{"nume":"Alexander Khoo"},{"nume":"Shelli Baida"},{"nume":"Sigal Tobias"},{"nume":"Guy Himuro"},{"nume":"Karen Colmenares"}]}' doc from dual
)
select jt.*
from json_data jd,
JSON_TABLE(jd.doc,'$.employees[*]' error on error
    columns(
        name varchar2(20) path '$.nume'
    )
) jt;


CREATE TABLE fruit_store (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data CLOB CHECK (data IS JSON)
);

INSERT INTO fruit_store (data) VALUES ('{"fruits": ["apple", "banana", "cherry"]}');
INSERT INTO fruit_store (data) VALUES ('{"fruits": ["apple", "kiwi"]}');
INSERT INTO fruit_store (data) VALUES ('{"fruits": ["cherry", "grape"]}');
COMMIT;


SELECT * 
FROM fruit_store
WHERE JSON_EXISTS(data, '$.fruits[*]?(@ == "cherry")');

--option 1
CREATE SEARCH INDEX fruits_idx ON fruit_store(data) FOR JSON;

--option 2
CREATE INDEX fruits_func_idx ON fruit_store (
  JSON_VALUE(data, '$.fruits[*]' RETURNING VARCHAR2(100))
);


SELECT *
FROM fruit_store,
     JSON_TABLE(
       data,
       '$.fruits[*]' COLUMNS (fruit VARCHAR2(50) PATH '$')
     ) jt
WHERE jt.fruit = 'cherry';

--xml
select xmltype(cursor(select * from employees)) from dual;
 
 SELECT XMLROOT(
  XMLELEMENT("employees",
    XMLAGG(
      XMLELEMENT("employee",
        XMLELEMENT("id", e.employee_id),
        XMLELEMENT("first_name", e.first_name),
        XMLELEMENT("last_name", e.last_name),
        XMLELEMENT("email", e.email)
      )
    )
  ),
  VERSION '1.0'
) AS xml_output
FROM employees e;


WITH xml_data AS (
  SELECT XMLTYPE('<?xml version="1.0"?>
<employees>
  <employee>
    <id>100</id>
    <first_name>Steven</first_name>
    <last_name>King</last_name>
    <email>SKING</email>
  </employee>
  <employee>
    <id>206</id>
    <first_name>William</first_name>
    <last_name>Gietz</last_name>
    <email>WGIETZ</email>
  </employee>
</employees>') AS doc
  FROM dual
)
SELECT xt.first_name||' '||xt.last_name
FROM xml_data xd,
     XMLTABLE(
       '/employees/employee'
       PASSING xd.doc
       COLUMNS
         id         NUMBER        PATH 'id',
         first_name VARCHAR2(50)  PATH 'first_name',
         last_name  VARCHAR2(50)  PATH 'last_name',
         email      VARCHAR2(50)  PATH 'email'
     ) xt;