CREATE TABLE employees2 (
    employee_id     NUMBER PRIMARY KEY,
    first_name      VARCHAR2(50),
    last_name       VARCHAR2(50),
    salary          NUMBER(10,2),
    commission_pct  NUMBER(4,2)
);

INSERT INTO employees2 (employee_id, first_name, last_name, salary, commission_pct)
VALUES (101, 'John', 'Smith', 5000, 0.10);

INSERT INTO employees2 (employee_id, first_name, last_name, salary, commission_pct)
VALUES (102, 'Maria', 'Johnson', 4200, NULL);

INSERT INTO employees2 (employee_id, first_name, last_name, salary, commission_pct)
VALUES (103, 'David', 'Brown', 6100, 0.15);

INSERT INTO employees2 (employee_id, first_name, last_name, salary, commission_pct)
VALUES (104, 'Ana', 'Davis', 3900, NULL);

INSERT INTO employees2 (employee_id, first_name, last_name, salary, commission_pct)
VALUES (105, 'Michael', 'Wilson', 7200, 0.20);

INSERT INTO employees2 (employee_id, first_name, last_name, salary, commission_pct)
VALUES (106, 'Elena', 'Moore', 4600, NULL);

INSERT INTO employees2 (employee_id, first_name, last_name, salary, commission_pct)
VALUES (107, 'Chris', 'Taylor', 5300, 0.05);

INSERT INTO employees2 (employee_id, first_name, last_name, salary, commission_pct)
VALUES (108, 'Sophia', 'Anderson', 6800, NULL);

INSERT INTO employees2 (employee_id, first_name, last_name, salary, commission_pct)
VALUES (109, 'Daniel', 'Thomas', 5700, 0.12);

INSERT INTO employees2 (employee_id, first_name, last_name, salary, commission_pct)
VALUES (110, 'Laura', 'Jackson', 4400, NULL);
/

--------------------------------------------------------------------------------

CREATE TABLE debug_log (
    log_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_time     TIMESTAMP DEFAULT SYSTIMESTAMP,
    module_name  VARCHAR2(100),
    line_no      NUMBER,
    log_message  VARCHAR2(4000),
    session_id   VARCHAR2(50) DEFAULT SYS_CONTEXT('USERENV', 'SESSIONID')
);

--------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE debug_util AS
    PROCEDURE enable_debug;
    PROCEDURE disable_debug;

    PROCEDURE log(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_log_message IN VARCHAR2
    );

    FUNCTION log_msg(p_message IN VARCHAR2) RETURN VARCHAR2;
    FUNCTION log_variable(p_name  IN VARCHAR2, p_value IN VARCHAR2) RETURN VARCHAR2;
    FUNCTION log_error(p_err  IN VARCHAR2) RETURN VARCHAR2;
    
END debug_util;
/

CREATE OR REPLACE PACKAGE BODY debug_util AS

    g_debug_mode BOOLEAN := FALSE;

    PROCEDURE enable_debug IS
    BEGIN
        g_debug_mode := TRUE;
    END enable_debug;

    PROCEDURE disable_debug IS
    BEGIN
        g_debug_mode := FALSE;
    END disable_debug;

    PROCEDURE log(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_log_message IN VARCHAR2
    ) IS
    BEGIN
        IF g_debug_mode THEN
            INSERT INTO debug_log (
                module_name,
                line_no,
                log_message
            )
            VALUES (
                p_module_name,
                p_line,
                p_log_message
            );
        END IF;
    END log;

    FUNCTION log_msg(
        p_message IN VARCHAR2
    ) RETURN VARCHAR2
    IS
    BEGIN
        RETURN p_message;
    END log_msg;

    FUNCTION log_variable(
        p_name  IN VARCHAR2,
        p_value IN VARCHAR2
    ) RETURN VARCHAR2
    IS
    BEGIN
        RETURN p_name || ' = ' || p_value;
    END log_variable;

    FUNCTION log_error(
        p_err  IN VARCHAR2
    ) RETURN VARCHAR2
    IS
    BEGIN
        RETURN 'ERROR: ' || p_err;
    END log_error;

END debug_util;
/

--------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE adjust_salaries_by_commission IS

    CURSOR c_emp IS
        SELECT employee_id, salary, commission_pct
        FROM employees2
        FOR UPDATE;

    v_new_salary employees2.salary%TYPE;

BEGIN
    debug_util.log(
        'adjust_salaries_by_commission',
        1,
        debug_util.log_msg('Procedure started')
    );

    FOR r_emp IN c_emp LOOP
        debug_util.log(
            'adjust_salaries_by_commission',
            17,
            debug_util.log_msg('Reading employee_id = ' || TO_CHAR(r_emp.employee_id) || ', salary = ' || TO_CHAR(r_emp.salary) || ', commission = ' || NVL(TO_CHAR(r_emp.commission_pct), 'NULL'))
        );

        IF r_emp.commission_pct IS NOT NULL THEN
            v_new_salary := r_emp.salary + (r_emp.salary * r_emp.commission_pct);

            debug_util.log(
                'adjust_salaries_by_commission',
                25,
                debug_util.log_msg('Commission exists. New salary calculated using commission_pct: ' || TO_CHAR(v_new_salary))
            );
        ELSE
            v_new_salary := r_emp.salary + (r_emp.salary * 0.02);

            debug_util.log(
                'adjust_salaries_by_commission',
                33,
                debug_util.log_msg('Commission is NULL. Applied default 2% increase. New salary: ' || TO_CHAR(v_new_salary))
            );
        END IF;

        UPDATE employees2
        SET salary = v_new_salary
        WHERE CURRENT OF c_emp;

        debug_util.log(
            'adjust_salaries_by_commission',
            42,
            debug_util.log_msg('Updated employee_id = ' || r_emp.employee_id || ' with new salary: ' || TO_CHAR(v_new_salary))
        );
    END LOOP;

    debug_util.log(
        'adjust_salaries_by_commission',
        53,
        debug_util.log_msg('Procedure completed')
    );

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        debug_util.log(
            'adjust_salaries_by_commission',
            62,
            debug_util.log_error(SQLERRM)
        );
        ROLLBACK;
        RAISE;
END adjust_salaries_by_commission;
/

--------------------------------------------------------------------------------

BEGIN
    debug_util.enable_debug;
END;
/

BEGIN
    adjust_salaries_by_commission;
END;
/

SELECT *
FROM debug_log
ORDER BY log_id;
/

BEGIN
    debug_util.disable_debug;
END;
/
